import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { PortalProvider } from '@/shared/providers/portal-context';

import Providers from '../shared/providers/providers';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background antialiased`}
      >
        <Providers>
          <PortalProvider containerId="modal-root">{children}</PortalProvider>
        </Providers>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
