alter table "public"."developer_file_operations" drop constraint "developer_file_operations_pkey";

drop index if exists "public"."developer_file_operations_pkey";

alter table "public"."developer_file_operations" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX developer_file_operations_pkey ON public.developer_file_operations USING btree (id);

alter table "public"."developer_file_operations" add constraint "developer_file_operations_pkey" PRIMARY KEY using index "developer_file_operations_pkey";


